version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testdb1
      # MYSQL_USER: user1
      # MYSQL_PASSWORD: 12345
      # MYSQL_ROOT_HOST: '%'
    ports: 
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  spring_app:
    image: my_spring_test
    container_name: springboot_testapp
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/testdb1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345      
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
